<?php

use Illuminate\Database\Seeder;
use App\Location_region_district;

class Location_regions_districtsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    private $array = array(
        ['region_id' => '1','alias' => 'Vinnitskiy','name' => 'Винницкий','translit' => 'Vinnitskiy','available' => 'yes'],
        ['region_id' => '1','alias' => 'Gaysinskiy','name' => 'Гайсинский','translit' => 'Gaysinskiy','available' => 'yes'],
        ['region_id' => '1','alias' => 'Zhmerinskiy','name' => 'Жмеринский','translit' => 'Zhmerinskiy','available' => 'yes'],
        ['region_id' => '1','alias' => 'Mogilev-Podolskiy','name' => 'Могилев-Подольский','translit' => 'Mogilev-Podolskiy','available' => 'yes'],
        ['region_id' => '1','alias' => 'Tulchinskiy','name' => 'Тульчинский','translit' => 'Tulchinskiy','available' => 'yes'],
        ['region_id' => '1','alias' => 'Khmelnitskiy','name' => 'Хмельницкий','translit' => 'Khmelnitskiy','available' => 'yes'],
        ['region_id' => '2','alias' => 'Berezovskiy','name' => 'Березовский','translit' => 'Berezovskiy','available' => 'yes'],
        ['region_id' => '2','alias' => 'Belgorod-Dnestrovskiy','name' => 'Белгород-Днестровский','translit' => 'Belgorod-Dnestrovskiy','available' => 'yes'],
        ['region_id' => '2','alias' => 'Bolgradskiy','name' => 'Болградский','translit' => 'Bolgradskiy','available' => 'yes'],
        ['region_id' => '2','alias' => 'Izmailskiy','name' => 'Измаильский','translit' => 'Izmailskiy','available' => 'yes'],
        ['region_id' => '2','alias' => 'Odesskiy','name' => 'Одесский','translit' => 'Odesskiy','available' => 'yes'],
        ['region_id' => '2','alias' => 'Podolskiy','name' => 'Подольский','translit' => 'Podolskiy','available' => 'yes'],
        ['region_id' => '2','alias' => 'Razdelnianskiy','name' => 'Раздельнянский','translit' => 'Razdelnianskiy','available' => 'yes'],
        ['region_id' => '3','alias' => 'Kremenchugskiy','name' => 'Кременчугский','translit' => 'Kremenchugskiy','available' => 'yes'],
        ['region_id' => '3','alias' => 'Lubenskiy','name' => 'Лубенский','translit' => 'Lubenskiy','available' => 'yes'],
        ['region_id' => '3','alias' => 'Mirgorodskiy','name' => 'Миргородский','translit' => 'Mirgorodskiy','available' => 'yes'],
        ['region_id' => '3','alias' => 'Poltavskiy','name' => 'Полтавский','translit' => 'Poltavskiy','available' => 'yes'],
        ['region_id' => '4','alias' => 'Varskiy','name' => 'Вараский','translit' => 'Varskiy','available' => 'yes'],
        ['region_id' => '4','alias' => 'Dubenskiy','name' => 'Дубенский','translit' => 'Dubenskiy','available' => 'yes'],
        ['region_id' => '4','alias' => 'Rovenskiy','name' => 'Ровенский','translit' => 'Rovenskiy','available' => 'yes'],
        ['region_id' => '4','alias' => 'Sarnenskiy','name' => 'Сарненский','translit' => 'Sarnenskiy','available' => 'yes'],
        ['region_id' => '5','alias' => 'Konotopskiy','name' => 'Конотопский','translit' => 'Konotopskiy','available' => 'yes'],
        ['region_id' => '5','alias' => 'Akhturskiy','name' => 'Ахтырский','translit' => 'Akhturskiy','available' => 'yes'],
        ['region_id' => '5','alias' => 'Romenskiy','name' => 'Роменский','translit' => 'Romenskiy','available' => 'yes'],
        ['region_id' => '5','alias' => 'Sumskoy','name' => 'Сумской','translit' => 'Sumskoy','available' => 'yes'],
        ['region_id' => '5','alias' => 'Shostkinskiy','name' => 'Шосткинский','translit' => 'Shostkinskiy','available' => 'yes'],
        ['region_id' => '6','alias' => 'Kremenetskiy','name' => 'Кременецкий','translit' => 'Kremenetskiy','available' => 'yes'],
        ['region_id' => '6','alias' => 'Ternopolskiy','name' => 'Тернопольский','translit' => 'Ternopolskiy','available' => 'yes'],
        ['region_id' => '6','alias' => 'Chertkovskiy','name' => 'Чертковский','translit' => 'Chertkovskiy','available' => 'yes'],
        ['region_id' => '7','alias' => 'Bogoduhovskiy','name' => 'Богодуховский','translit' => 'Bogoduhovskiy','available' => 'yes'],
        ['region_id' => '7','alias' => 'Izumskiy','name' => 'Изюмский','translit' => 'Izumskiy','available' => 'yes'],
        ['region_id' => '7','alias' => 'Krasnogradskiy','name' => 'Красноградский','translit' => 'Krasnogradskiy','available' => 'yes'],
        ['region_id' => '7','alias' => 'Kupianskiy','name' => 'Купянский','translit' => 'Kupianskiy','available' => 'yes'],
        ['region_id' => '7','alias' => 'Lozovskiy','name' => 'Лозовский','translit' => 'Lozovskiy','available' => 'yes'],
        ['region_id' => '7','alias' => 'Kharkovskiy','name' => 'Харьковский','translit' => 'Kharkovskiy','available' => 'yes'],
        ['region_id' => '7','alias' => 'Chuguevskiy','name' => 'Чугуевский','translit' => 'Chuguevskiy','available' => 'yes'],
        ['region_id' => '8','alias' => 'Berislavskiy','name' => 'Бериславский','translit' => 'Berislavskiy','available' => 'yes'],
        ['region_id' => '8','alias' => 'Genicheskiy','name' => 'Генический','translit' => 'Genicheskiy','available' => 'yes'],
        ['region_id' => '8','alias' => 'Kahovskiy','name' => 'Каховский','translit' => 'Kahovskiy','available' => 'yes'],
        ['region_id' => '8','alias' => 'Skadovskiy','name' => 'Скадовский','translit' => 'Skadovskiy','available' => 'yes'],
        ['region_id' => '8','alias' => 'Khersonskiy','name' => 'Херсонский','translit' => 'Khersonskiy','available' => 'yes'],
        ['region_id' => '9','alias' => 'Kamenets-Podolskiy','name' => 'Каменец-Подольский','translit' => 'Kamenets-Podolskiy','available' => 'yes'],
        ['region_id' => '9','alias' => 'Khmelnitskiy','name' => 'Хмельницкий','translit' => 'Khmelnitskiy','available' => 'yes'],
        ['region_id' => '9','alias' => 'Shepetovskiy','name' => 'Шепетовский','translit' => 'Shepetovskiy','available' => 'yes'],
        ['region_id' => '10','alias' => 'Zvenigorodskiy','name' => 'Звенигородский','translit' => 'Zvenigorodskiy','available' => 'yes'],
        ['region_id' => '10','alias' => 'Zolotonoshskiy','name' => 'Золотоношский','translit' => 'Zolotonoshskiy','available' => 'yes'],
        ['region_id' => '10','alias' => 'Umanskiy','name' => 'Уманский','translit' => 'Umanskiy','available' => 'yes'],
        ['region_id' => '10','alias' => 'Cherkasskiy','name' => 'Черкасский','translit' => 'Cherkasskiy','available' => 'yes'],
        ['region_id' => '24','alias' => 'Vuzhnitskiy','name' => 'Вижницкий','translit' => 'Vuzhnitskiy','available' => 'yes'],
        ['region_id' => '24','alias' => 'Dnestrovskiy','name' => 'Днестровский','translit' => 'Dnestrovskiy','available' => 'yes'],
        ['region_id' => '24','alias' => 'Chernovitskiy','name' => 'Черновицкий','translit' => 'Chernovitskiy','available' => 'yes'],
        ['region_id' => '11','alias' => 'Korukovskiy','name' => 'Корюковский','translit' => 'Korukovskiy','available' => 'yes'],
        ['region_id' => '11','alias' => 'Nezhinskiy','name' => 'Нежинский','translit' => 'Nezhinskiy','available' => 'yes'],
        ['region_id' => '11','alias' => 'Novgorod-Severskiy','name' => 'Новгород-Северский','translit' => 'Novgorod-Severskiy','available' => 'yes'],
        ['region_id' => '11','alias' => 'Prilutskiy','name' => 'Прилуцкий','translit' => 'Prilutskiy','available' => 'yes'],
        ['region_id' => '11','alias' => 'Chernigovskiy','name' => 'Черниговский','translit' => 'Chernigovskiy','available' => 'yes'],
        ['region_id' => '12','alias' => 'Bashtanskiy','name' => 'Баштанский','translit' => 'Bashtanskiy','available' => 'yes'],
        ['region_id' => '12','alias' => 'Voznesenskiy','name' => 'Вознесенский','translit' => 'Voznesenskiy','available' => 'yes'],
        ['region_id' => '12','alias' => 'Nikolaevskiy','name' => 'Николаевский','translit' => 'Nikolaevskiy','available' => 'yes'],
        ['region_id' => '12','alias' => 'Pervomayskiy','name' => 'Первомайский','translit' => 'Pervomayskiy','available' => 'yes'],
        ['region_id' => '13','alias' => 'Drogobuchskiy','name' => 'Дрогобычский','translit' => 'Drogobuchskiy','available' => 'yes'],
        ['region_id' => '13','alias' => 'Zolochevskiy','name' => 'Золочевский','translit' => 'Zolochevskiy','available' => 'yes'],
        ['region_id' => '13','alias' => 'Lvovskiy','name' => 'Львовский','translit' => 'Lvovskiy','available' => 'yes'],
        ['region_id' => '13','alias' => 'Samborskiy','name' => 'Самборский','translit' => 'Samborskiy','available' => 'yes'],
        ['region_id' => '13','alias' => 'Struyskiy','name' => 'Стрыйский','translit' => 'Struyskiy','available' => 'yes'],
        ['region_id' => '13','alias' => 'Chervonogradskiy','name' => 'Червоноградский','translit' => 'Chervonogradskiy','available' => 'yes'],
        ['region_id' => '13','alias' => 'Javorovskiy','name' => 'Яворовский','translit' => 'Javorovskiy','available' => 'yes'],
        ['region_id' => '14','alias' => 'Alchevskiy','name' => 'Алчевский','translit' => 'Alchevskiy','available' => 'no'],
        ['region_id' => '14','alias' => 'Dovzhanskiy','name' => 'Довжанский','translit' => 'Dovzhanskiy','available' => 'no'],
        ['region_id' => '14','alias' => 'Luganskiy','name' => 'Луганский','translit' => 'Luganskiy','available' => 'no'],
        ['region_id' => '14','alias' => 'Rovenkovskiy','name' => 'Ровеньковский','translit' => 'Rovenkovskiy','available' => 'no'],
        ['region_id' => '14','alias' => 'Svatovskiy','name' => 'Сватовский','translit' => 'Svatovskiy','available' => 'yes'],
        ['region_id' => '14','alias' => 'Severodetskiy','name' => 'Северодонецкий','translit' => 'Severodetskiy','available' => 'yes'],
        ['region_id' => '14','alias' => 'Starobelskiy','name' => 'Старобельский','translit' => 'Starobelskiy','available' => 'yes'],
        ['region_id' => '14','alias' => 'Schastienskiy','name' => 'Счастьенский','translit' => 'Schastienskiy','available' => 'yes'],
        ['region_id' => '15','alias' => 'Vladimir-Volunskiy','name' => 'Владимир-Волынский','translit' => 'Vladimir-Volunskiy','available' => 'yes'],
        ['region_id' => '15','alias' => 'Kamen-Kashirskiy','name' => 'Камень-Каширский','translit' => 'Kamen-Kashirskiy','available' => 'yes'],
        ['region_id' => '15','alias' => 'Kovalskiy','name' => 'Ковальский','translit' => 'Kovalskiy','available' => 'yes'],
        ['region_id' => '15','alias' => 'Lutskiy','name' => 'Луцкий','translit' => 'Lutskiy','available' => 'yes'],
        ['region_id' => '16','alias' => 'Dneprovskiy','name' => 'Днепровский','translit' => 'Dneprovskiy','available' => 'yes'],
        ['region_id' => '16','alias' => 'Kamenskiy','name' => 'Каменский','translit' => 'Kamenskiy','available' => 'yes'],
        ['region_id' => '16','alias' => 'Krivorozhskiy','name' => 'Криворожский','translit' => 'Krivorozhskiy','available' => 'yes'],
        ['region_id' => '16','alias' => 'Nikopolskiy','name' => 'Никопольский','translit' => 'Nikopolskiy','available' => 'yes'],
        ['region_id' => '16','alias' => 'Novomoskovskiy','name' => 'Новомосковский','translit' => 'Novomoskovskiy','available' => 'yes'],
        ['region_id' => '16','alias' => 'Pavlogradskiy','name' => 'Павлоградский','translit' => 'Pavlogradskiy','available' => 'yes'],
        ['region_id' => '16','alias' => 'Sinelnikovskiy','name' => 'Синельниковский','translit' => 'Sinelnikovskiy','available' => 'yes'],
        ['region_id' => '17','alias' => 'Volnovahskiy','name' => 'Волновахский','translit' => 'Volnovahskiy','available' => 'yes'],
        ['region_id' => '17','alias' => 'Gorlovskiy','name' => 'Горловский','translit' => 'Gorlovskiy','available' => 'no'],
        ['region_id' => '17','alias' => 'Donetskiy','name' => 'Донецкий','translit' => 'Donetskiy','available' => 'no'],
        ['region_id' => '17','alias' => 'Kalmiusskiy','name' => 'Кальмиусский','translit' => 'Kalmiusskiy','available' => 'no'],
        ['region_id' => '17','alias' => 'Kramatorskiy','name' => 'Краматорский','translit' => 'Kramatorskiy','available' => 'yes'],
        ['region_id' => '17','alias' => 'Mariupolskiy','name' => 'Мариупольский','translit' => 'Mariupolskiy','available' => 'yes'],
        ['region_id' => '17','alias' => 'Bahmutskiy','name' => 'Бахмутский','translit' => 'Bahmutskiy','available' => 'yes'],
        ['region_id' => '17','alias' => 'Pokrovskiy','name' => 'Покровский','translit' => 'Pokrovskiy','available' => 'yes'],
        ['region_id' => '18','alias' => 'Berdichevskiy','name' => 'Бердичевский','translit' => 'Berdichevskiy','available' => 'yes'],
        ['region_id' => '18','alias' => 'Zhitomirskiy','name' => 'Житомирский','translit' => 'Zhitomirskiy','available' => 'yes'],
        ['region_id' => '18','alias' => 'Korostenskiy','name' => 'Коростенский','translit' => 'Korostenskiy','available' => 'yes'],
        ['region_id' => '18','alias' => 'Novgorod-Voluskiy','name' => 'Новоград-Волынский','translit' => 'Novgorod-Voluskiy','available' => 'yes'],
        ['region_id' => '19','alias' => 'Beregovskiy','name' => 'Береговский','translit' => 'Beregovskiy','available' => 'yes'],
        ['region_id' => '19','alias' => 'Mukachevskiy','name' => 'Мукачевский','translit' => 'Mukachevskiy','available' => 'yes'],
        ['region_id' => '19','alias' => 'Rahovskiy','name' => 'Раховский','translit' => 'Rahovskiy','available' => 'yes'],
        ['region_id' => '19','alias' => 'Tiachevskiy','name' => 'Тячевский','translit' => 'Tiachevskiy','available' => 'yes'],
        ['region_id' => '19','alias' => 'Uzhgorodskiy','name' => 'Ужгородский','translit' => 'Uzhgorodskiy','available' => 'yes'],
        ['region_id' => '19','alias' => 'Khustskiy','name' => 'Хустский','translit' => 'Khustskiy','available' => 'yes'],
        ['region_id' => '20','alias' => 'Berdianskiy','name' => 'Бердянский','translit' => 'Berdianskiy','available' => 'yes'],
        ['region_id' => '20','alias' => 'Vasilievskiy','name' => 'Васильевский','translit' => 'Vasilievskiy','available' => 'yes'],
        ['region_id' => '20','alias' => 'Zaporozhskiy','name' => 'Запорожский','translit' => 'Zaporozhskiy','available' => 'yes'],
        ['region_id' => '20','alias' => 'Melitopolskiy','name' => 'Мелитопольский','translit' => 'Melitopolskiy','available' => 'yes'],
        ['region_id' => '20','alias' => 'Pologovskiy','name' => 'Пологовский','translit' => 'Pologovskiy','available' => 'yes'],
        ['region_id' => '21','alias' => 'Verhovinskiy','name' => 'Верховинский','translit' => 'Verhovinskiy','available' => 'yes'],
        ['region_id' => '21','alias' => 'Ivano-Frankovskiy','name' => 'Ивано-Франковский','translit' => 'Ivano-Frankovskiy','available' => 'yes'],
        ['region_id' => '21','alias' => 'Kalushskiy','name' => 'Калушский','translit' => 'Kalushskiy','available' => 'yes'],
        ['region_id' => '21','alias' => 'Kolomutskiy','name' => 'Коломыйский','translit' => 'Kolomutskiy','available' => 'yes'],
        ['region_id' => '21','alias' => 'Kosovskiy','name' => 'Косовский','translit' => 'Kosovskiy','available' => 'yes'],
        ['region_id' => '21','alias' => 'Nadvornianskiy','name' => 'Надворнянский','translit' => 'Nadvornianskiy','available' => 'yes'],
        ['region_id' => '22','alias' => 'Borispolskiy','name' => 'Бориспольский','translit' => 'Borispolskiy','available' => 'yes'],
        ['region_id' => '22','alias' => 'Brovarskiy','name' => 'Броварский','translit' => 'Brovarskiy','available' => 'yes'],
        ['region_id' => '22','alias' => 'Buchanskiy','name' => 'Бучанский','translit' => 'Buchanskiy','available' => 'yes'],
        ['region_id' => '22','alias' => 'Vushgorodskiy','name' => 'Вышгородский','translit' => 'Vushgorodskiy','available' => 'yes'],
        ['region_id' => '22','alias' => 'Belotserkovskiy','name' => 'Белоцерковский','translit' => 'Belotserkovskiy','available' => 'yes'],
        ['region_id' => '22','alias' => 'Obuhovskiy','name' => 'Обуховский','translit' => 'Obuhovskiy','available' => 'yes'],
        ['region_id' => '22','alias' => 'Fastovskiy','name' => 'Фастовский','translit' => 'Fastovskiy','available' => 'yes'],
        ['region_id' => '23','alias' => 'Golovanovskiy','name' => 'Головановский','translit' => 'Golovanovskiy','available' => 'yes'],
        ['region_id' => '23','alias' => 'Kropivnitskiy','name' => 'Кропивницкий','translit' => 'Kropivnitskiy','available' => 'yes'],
        ['region_id' => '23','alias' => 'Novoukrainskiy','name' => 'Новоукраинский','translit' => 'Novoukrainskiy','available' => 'yes'],
        ['region_id' => '23','alias' => 'Aleksandriyskiy','name' => 'Александрийский','translit' => 'Aleksandriyskiy','available' => 'yes'],
        ['region_id' => '26','alias' => 'Bahchisarayskiy','name' => 'Бахчисарайский','translit' => 'Bahchisarayskiy','available' => 'no'],
        ['region_id' => '26','alias' => 'Belogorskiy','name' => 'Белогорский','translit' => 'Belogorskiy','available' => 'no'],
        ['region_id' => '26','alias' => 'Dzhankoyskiy','name' => 'Джанкойский','translit' => 'Dzhankoyskiy','available' => 'no'],
        ['region_id' => '26','alias' => 'Evpatoriyskiy','name' => 'Евпаторийский','translit' => 'Evpatoriyskiy','available' => 'no'],
        ['region_id' => '26','alias' => 'Kerchenskiy','name' => 'Керченский','translit' => 'Kerchenskiy','available' => 'no'],
        ['region_id' => '26','alias' => 'Kurmanskiy','name' => 'Курманский','translit' => 'Kurmanskiy','available' => 'no'],
        ['region_id' => '26','alias' => 'Perekopskiy','name' => 'Перекопский','translit' => 'Perekopskiy','available' => 'no'],
        ['region_id' => '26','alias' => 'Simferopolskiy','name' => 'Симферопольский','translit' => 'Simferopolskiy','available' => 'no'],
        ['region_id' => '26','alias' => 'Pheodosiyskiy','name' => 'Феодосийский','translit' => 'Pheodosiyskiy','available' => 'no'],
        ['region_id' => '26','alias' => 'Jaltinskiy','name' => 'Ялтинский','translit' => 'Jaltinskiy','available' => 'no'],
    );
    public function run()
    {
        foreach($this->array as $value) {
            Location_region_district::create($value);
        }
    }
}
